# Generated by Django 4.0.4 on 2022-07-13 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_comment_author_comment_modify_date_comment_voter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='voter',
        ),
        migrations.AddField(
            model_name='news',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='fact',
            field=models.ManyToManyField(blank=True, null=True, related_name='fact_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='fake',
            field=models.ManyToManyField(blank=True, null=True, related_name='fake_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
