export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEWS_COIN_DETAIL_REQUEST = "NEWS_COIN_DETAIL_REQUESTS";
export const NEWS_COIN_DETAIL_SUCCESS = "NEWS_COIN_DETAIL_SUCCESSS";
export const NEWS_COIN_DETAIL_FAIL = "NEWS_COIN_DETAIL_FAIL";

export const NEWS_CREATE_REQUEST = "NEWS_CREATE_REQUEST";
export const NEWS_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS";
export const NEWS_CREATE_FAIL = "NEWS_CREATE_FAIL";
export const NEWS_CREATE_RESET = "NEWS_CREATE_RESET";
