export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEWS_COIN_DETAIL_REQUEST = "NEWS_COIN_DETAIL_REQUESTS";
export const NEWS_COIN_DETAIL_SUCCESS = "NEWS_COIN_DETAIL_SUCCESSS";
export const NEWS_COIN_DETAIL_FAIL = "NEWS_COIN_DETAIL_FAIL";

export const NEWS_CREATE_REQUEST = "  NEWS_CREATE_REQUEST";
export const NEWS_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS";
export const NEWS_CREATE_FAIL = "NEWS_CREATE_FAIL";
export const NEWS_CREATE_RESET = "NEWS_CREATE_RESET";

export const NEWS_UPDATE_REQUEST = "NEWS_UPDATE_REQUEST";
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";
export const NEWS_UPDATE_RESET = "NEWS_UPDATE_RESET";

export const NEWS_DELETE_REQUEST = "NEWS_DELETE_REQUEST";
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS";
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL";

export const NEWS_DETAILS_REQUEST = "NEWS_DETAILS=REQUEST";
export const NEWS_DETAILS_SUCCESS = "NEWS_DETAILS=SUCCESS";
export const NEWS_DETAILS_FAIL = "NEWS_DETAILS=FAIL";
export const NEWS_DETAILS_RESET = "NEWS_DETAILS=RESET";

export const NEWS_LIKE_REQUEST = "NEWS_LIKE_REQUEST";
export const NEWS_LIKE_SUCCESS = "NEWS_LIKE_SUCCESS";
export const NEWS_LIKE_FAIL = "NEWS_LIKE_FAIL";

export const NEWS_DISLIKE_REQUEST = "NEW_DISLIKE_REQUEST";
export const NEWS_DISLIKE_SUCCESS = "NEW_DISLIKE_SUCCESS";
export const NEWS_DISLIKE_FAIL = "NEW_DISLIKE_FAIL";

export const NEWS_FACT_REQUEST = "NEWS_FACT_REQUEST";
export const NEWS_FACT_SUCCESS = "NEWS_FACT_SUCCESS";
export const NEWS_FACT_FAIL = "NEWS_FACT_FAIL";

export const NEWS_FAKE_REQUEST = "NEWS_FAKE_REQUEST";
export const NEWS_FAKE_SUCCESS = "NEWS_FAKE_SUCCESS";
export const NEWS_FAKE_FAIL = "NEWS_FAKE_FAIL";

export const NEWS_UNLIKE_REQUEST = "NEWS_UNLIKE_REQUEST";
export const NEWS_UNLIKE_SUCCESS = "NEWS_UNLIKE_SUCCESS";
export const NEWS_UNLIKE_FAIL = "NEWS_UNLIKE_FAIL";

export const NEWS_UNDISLIKE_REQUEST = "NEWS_UNDISLIKE_REQUEST";
export const NEWS_UNDISLIKE_SUCCESS = "NEWS_UNDISLIKE_SUCCESS";
export const NEWS_UNDISLIKE_FAIL = "NEWS_UNDISLIKE_FAIL";

export const NEWS_UNFACT_REQUEST = "NEWS_UNFACT_REQUEST";
export const NEWS_UNFACT_SUCCESS = "NEWS_UNFACT_SUCCESS";
export const NEWS_UNFACT_FAIL = "NEWS_UNFACT_FAIL";

export const NEWS_UNFAKE_REQUEST = "NEWS_UNFAKE_REQUEST";
export const NEWS_UNFAKE_SUCCESS = "NEWS_UNFAKE_SUCCESS";
export const NEWS_UNFAKE_FAIL = "NEWS_UNFAKE_FAIL";

export const COIN_NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const COIN_NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const COIN_NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

//hi
